FROM maven:3.8.5-openjdk-17

ENV HELM_VERSION="v2.17.0" \
    YQ_VERSION="2.1.1" \
    ANT_VERSION=1.10.2 \
    ANT_HOME=/usr/share/ant \
    DOCKER_VERSION="20.10.9"

WORKDIR /tmp

RUN microdnf install wget \
    && curl -fs "http://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz" -o ant.tar.gz \
    && tar -zxf ant.tar.gz -C /usr/share/ >> /dev/null \
    && ln -s /usr/share/apache-ant-${ANT_VERSION} /usr/share/ant \
    && rm -f ant.tar.gz \
    && ln -s /usr/share/ant/bin/ant /usr/bin/ant \
    && curl -fsSL "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64" -o /usr/bin/yq \
    && chmod +x /usr/bin/yq \
    && curl -fsSL "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
    && tar -xzvf docker.tgz -C /tmp \
    && rm -f docker.tgz \
    && cp /tmp/docker/docker /usr/bin/docker \
    && rm -rf /tmp/docker \
    && curl -fsSL "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" -o helm.tar.gz \
    && tar -zxf helm.tar.gz -C /tmp \
    && rm -r helm.tar.gz \
    && mv /tmp/linux-amd64/helm /usr/bin/helm \
    && helm init -c \
    && helm plugin install https://github.com/chartmuseum/helm-push --version v0.8.1
    
